spring:
  ###################### mysql ###########################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nideshop?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

#小程序ID
wx:
  appId:
  #小程序密钥
  secret:
  #商户号
  mchId:
  #支付签名
  paySignKey:
  #交易类型
  tradeType: JSAPI
  #证书名称，对应不同的商户号
  certName: /cert/apiclient_cert.p12
  #支付回调地址
  notifyUrl: https://www.fly2you.cn/admin/url/api/notify
  #获取code的请求地址
  getCode: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=STAT#wechat_redirect
  #获取Web_access_tokenhttps的请求地址
  webAccessTokenhttps:  https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
  #拉取用户信息的请求地址
  userMessage: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN
  #微信统一下单接口路径
  uniformorder: https://api.mch.weixin.qq.com/pay/unifiedorder
  #退款地址
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  #退款查询地址
  refundqueryUrl: https://api.mch.weixin.qq.com/pay/refundquery
  #微信查询订单状态
  orderquery: https://api.mch.weixin.qq.com/pay/orderquery

#安全起见，暴露的短信接口需要配置有效的请求IP
sms:
  validIp: 127.0.0.1

#演示环境  1：是  0：否
sys:
  demo: 0